### ISSUE TITLE
Select in draggable component

### ISSUE THREAD

**Issue by RassaLibre** [bevacqua/react-dragula#1]
Hi guys,
just a weirdness I observed. I have a component which is draggable (you can drag & drop it somewhere) and inside of that component I have a simple select. When I try to open the select to see all the options it just does not work. It does not show the options. I guess it is not a desired behaviour because, well I am not able to change the value of the select. I am currently doing something like this to make this work:

```
moves: function(el, source, handle){
    if(handle.className.indexOf('exercise-collection-type') > -1) return false;
    else return true;
  } 
```

'exercise-collection-type' is a class of the select so I know that when I grab it by the select, I do not want to drag & drop. Is this ok or a bug? I can provide jsfiddle, but I guess the description is straight forward.

Thanks!

**Comment by bevacqua** [comment]
Yeah a fiddle would be useful here, but also please move this issue to `dragula` itself.
