### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by unHuesio** [bevacqua/react-dragula#6]
I'm getting this error when compiling my react project with gulp, tought it was a linting problem but apparently not.

ReferenceError: document is not defined

**Comment by unHuesio** [comment]
Issue was with fluxible and server side rendering, just needed to import lib directly on the componentDidMount

**Comment by vitorhugoanjos** [comment]
@abFx How exactly did you import the lib directly on the componentDidMount?

**Comment by jose920405** [comment]
+1

**Comment by U1320100568** [comment]
it has NOT resolved
